Fix pollard serialization/deserialization ( #46)
mit-dci/rustreexo pull request #47
Opened 2024-04-24 13:26 UTC by Ash-L2L

fixes #46

2024-05-16 07:05 UTC, Davidson-Souza commented
Thank you for this PR! Just some comments

2024-05-16 07:08 UTC, Davidson-Souza requested changes

2024-05-16 07:08 UTC, Davidson-Souza commented on Cargo.toml
> +version = "0.2.0"
Not sure if we should do this here. We probably need another release, but let's do it in another pr

2024-05-16 07:08 UTC, Davidson-Souza commented on src/accumulator/pollard.rs
> +    use std::task::Poll;
I think this shouldn't be here.

2024-05-16 07:08 UTC, Davidson-Souza commented on src/accumulator/pollard.rs
> +    }
Can we `assert` the roots here?

2024-05-16 17:28 UTC, Ash-L2L commented on src/accumulator/pollard.rs
> +    }
Done, resolving

2024-05-16 17:28 UTC, Ash-L2L commented on src/accumulator/pollard.rs
> +    use std::task::Poll;
Removed, resolving

2024-05-20 07:01 UTC, Davidson-Souza approved these changes

2024-05-20 08:15 UTC, merged